name: .NET Core
 
 
on: [push]
 
 
jobs:
  build:
 
 
    runs-on: windows-latest
 
 
    steps:
    - uses: actions/checkout@v3
      with:
          ref: "6.0.7_Build"
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
      
    - name: Build
      run: .\build.cmd -a x64 -c Release
